/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v10.0
processor: S32K144
package_id: S32K144_LQFP100
mcu_data: s32sdk_s32k1xx_rtm_403
processor_version: 0.0.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 33afab84-3987-42cd-bca4-67126556733a
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "peripherals_adc_config_1.h"

/*******************************************************************************
 * adc_config_1 initialization code
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'adc_config_1'
- type: 'adc_config'
- mode: 'general'
- custom_name_enabled: 'true'
- type_id: 'adc'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'ADC_0'
- config_sets:
  - adc:
    - adcConverterCfg:
      - 0:
        - name: 'adc_config_1_ConvConfig0'
        - readonly: 'true'
        - clockDivide: 'ADC_CLK_DIVIDE_1'
        - sampleTime: '12'
        - resolution: 'ADC_RESOLUTION_12BIT'
        - inputClock: 'ADC_CLK_ALT_1'
        - trigger: 'ADC_TRIGGER_HARDWARE'
        - pretriggerSel: 'ADC_PRETRIGGER_SEL_TRGMUX'
        - triggerSel: 'ADC_TRIGGER_SEL_TRGMUX'
        - dmaEnable: 'false'
        - voltageRef: 'ADC_VOLTAGEREF_VREF'
        - continuousConvEnable: 'false'
        - supplyMonitoringEnable: 'false'
      - 1:
        - name: 'adc_config_1_ConvConfig1'
        - readonly: 'true'
        - clockDivide: 'ADC_CLK_DIVIDE_1'
        - sampleTime: '12'
        - resolution: 'ADC_RESOLUTION_12BIT'
        - inputClock: 'ADC_CLK_ALT_1'
        - trigger: 'ADC_TRIGGER_SOFTWARE'
        - pretriggerSel: 'ADC_PRETRIGGER_SEL_TRGMUX'
        - triggerSel: 'ADC_TRIGGER_SEL_TRGMUX'
        - dmaEnable: 'false'
        - voltageRef: 'ADC_VOLTAGEREF_VREF'
        - continuousConvEnable: 'false'
        - supplyMonitoringEnable: 'false'
      - 2:
        - name: 'adc_config_1_ConvConfig2'
        - readonly: 'true'
        - clockDivide: 'ADC_CLK_DIVIDE_1'
        - sampleTime: '12'
        - resolution: 'ADC_RESOLUTION_12BIT'
        - inputClock: 'ADC_CLK_ALT_1'
        - trigger: 'ADC_TRIGGER_SOFTWARE'
        - pretriggerSel: 'ADC_PRETRIGGER_SEL_TRGMUX'
        - triggerSel: 'ADC_TRIGGER_SEL_TRGMUX'
        - dmaEnable: 'false'
        - voltageRef: 'ADC_VOLTAGEREF_VREF'
        - continuousConvEnable: 'false'
        - supplyMonitoringEnable: 'false'
      - 3:
        - name: 'adc_config_1_ConvConfig3'
        - readonly: 'true'
        - clockDivide: 'ADC_CLK_DIVIDE_1'
        - sampleTime: '12'
        - resolution: 'ADC_RESOLUTION_12BIT'
        - inputClock: 'ADC_CLK_ALT_1'
        - trigger: 'ADC_TRIGGER_SOFTWARE'
        - pretriggerSel: 'ADC_PRETRIGGER_SEL_TRGMUX'
        - triggerSel: 'ADC_TRIGGER_SEL_TRGMUX'
        - dmaEnable: 'false'
        - voltageRef: 'ADC_VOLTAGEREF_VREF'
        - continuousConvEnable: 'false'
        - supplyMonitoringEnable: 'false'
    - adcCompareCfg:
      - 0:
        - name: 'adc_config_1_HwCompConfig0'
        - readonly: 'true'
        - compareEnable: 'true'
        - compareGreaterThanEnable: 'true'
        - compareRangeFuncEnable: 'false'
        - compVal1: '2048'
        - compVal2: '0'
    - adcAverageCfg: []
    - adcChanCfg:
      - 0:
        - name: 'adc_config_1_ChnConfig0'
        - readonly: 'true'
        - interruptEnable: 'true'
        - channel: 'ADC_INPUTCHAN_EXT12'
      - 1:
        - name: 'adc_config_1_ChnConfig1'
        - readonly: 'true'
        - interruptEnable: 'true'
        - channel: 'ADC_INPUTCHAN_EXT12'
      - 2:
        - name: 'adc_config_1_ChnConfig2'
        - readonly: 'true'
        - interruptEnable: 'true'
        - channel: 'ADC_INPUTCHAN_EXT12'
      - 3:
        - name: 'adc_config_1_ChnConfig3'
        - readonly: 'true'
        - interruptEnable: 'true'
        - channel: 'ADC_INPUTCHAN_EXT12'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files in application code.
 *
 */

const adc_converter_config_t adc_config_1_ConvConfig0 = {
  .clockDivide = ADC_CLK_DIVIDE_1,
  .sampleTime = 12U,
  .resolution = ADC_RESOLUTION_12BIT,
  .inputClock = ADC_CLK_ALT_1,
  .trigger = ADC_TRIGGER_HARDWARE,
  .pretriggerSel = ADC_PRETRIGGER_SEL_TRGMUX,
  .triggerSel = ADC_TRIGGER_SEL_TRGMUX,
  .dmaEnable = false,
  .voltageRef = ADC_VOLTAGEREF_VREF,
  .continuousConvEnable = false,
  .supplyMonitoringEnable = false
};

const adc_converter_config_t adc_config_1_ConvConfig1 = {
  .clockDivide = ADC_CLK_DIVIDE_1,
  .sampleTime = 12U,
  .resolution = ADC_RESOLUTION_12BIT,
  .inputClock = ADC_CLK_ALT_1,
  .trigger = ADC_TRIGGER_SOFTWARE,
  .pretriggerSel = ADC_PRETRIGGER_SEL_TRGMUX,
  .triggerSel = ADC_TRIGGER_SEL_TRGMUX,
  .dmaEnable = false,
  .voltageRef = ADC_VOLTAGEREF_VREF,
  .continuousConvEnable = false,
  .supplyMonitoringEnable = false
};

const adc_converter_config_t adc_config_1_ConvConfig2 = {
  .clockDivide = ADC_CLK_DIVIDE_1,
  .sampleTime = 12U,
  .resolution = ADC_RESOLUTION_12BIT,
  .inputClock = ADC_CLK_ALT_1,
  .trigger = ADC_TRIGGER_SOFTWARE,
  .pretriggerSel = ADC_PRETRIGGER_SEL_TRGMUX,
  .triggerSel = ADC_TRIGGER_SEL_TRGMUX,
  .dmaEnable = false,
  .voltageRef = ADC_VOLTAGEREF_VREF,
  .continuousConvEnable = false,
  .supplyMonitoringEnable = false
};

const adc_converter_config_t adc_config_1_ConvConfig3 = {
  .clockDivide = ADC_CLK_DIVIDE_1,
  .sampleTime = 12U,
  .resolution = ADC_RESOLUTION_12BIT,
  .inputClock = ADC_CLK_ALT_1,
  .trigger = ADC_TRIGGER_SOFTWARE,
  .pretriggerSel = ADC_PRETRIGGER_SEL_TRGMUX,
  .triggerSel = ADC_TRIGGER_SEL_TRGMUX,
  .dmaEnable = false,
  .voltageRef = ADC_VOLTAGEREF_VREF,
  .continuousConvEnable = false,
  .supplyMonitoringEnable = false
};

const adc_compare_config_t adc_config_1_HwCompConfig0 = {
  .compareEnable = true,
  .compareGreaterThanEnable = true,
  .compareRangeFuncEnable = false,
  .compVal1 = 2048U,
  .compVal2 = 0U
};

const adc_chan_config_t adc_config_1_ChnConfig0 = {
  .interruptEnable = true,
  .channel = ADC_INPUTCHAN_EXT12
};

const adc_chan_config_t adc_config_1_ChnConfig1 = {
  .interruptEnable = true,
  .channel = ADC_INPUTCHAN_EXT12
};

const adc_chan_config_t adc_config_1_ChnConfig2 = {
  .interruptEnable = true,
  .channel = ADC_INPUTCHAN_EXT12
};

const adc_chan_config_t adc_config_1_ChnConfig3 = {
  .interruptEnable = true,
  .channel = ADC_INPUTCHAN_EXT12
};


